# -*- coding: utf-8 -*-
"""PINN Extension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185F7S6h6f9tenDJ66SfCkTsx8UQibnMV
"""

# ================================
# COMPLETE INTER-CHARACTER ANALYSIS
# SAVES RESULTS TO GOOGLE DRIVE
# ================================

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
import umap

# 3. Folder containing character files
folder_path = "/content/drive/MyDrive/Research_Paper_2/Character_Details/Character_role_tag_with_embeddings"

# Create results folder
results_path = os.path.join(folder_path, "results")
os.makedirs(results_path, exist_ok=True)

print("Results will be saved in:", results_path)

# 4. Load JSON files
data = {}

for file in os.listdir(folder_path):
    if file.endswith(".json"):
        char_name = file.replace(".json","")
        with open(os.path.join(folder_path,file),"r") as f:
            data[char_name] = json.load(f)

characters = list(data.keys())

print("Characters loaded:", characters)

# ======================================
# 5. Compute mean embedding per layer
# ======================================

layer_means = {}

for char, entries in data.items():

    layer_vectors = {i: [] for i in range(1,13)}

    for item in entries:

        emb = item["embeddings"]

        for l in range(1,13):
            layer_vectors[l].append(emb[f"layer_{l}"])

    means = []

    for l in range(1,13):
        means.append(np.mean(layer_vectors[l], axis=0))

    layer_means[char] = means

print("Layer trajectories computed")

# ======================================
# 6. Build trajectory vectors
# ======================================

trajectory_vectors = {}

for char in characters:
    trajectory_vectors[char] = np.concatenate(layer_means[char])

# ======================================
# 7. Compute ALL vs ALL similarity matrix
# ======================================

n = len(characters)
similarity_matrix = np.zeros((n,n))

for i,c1 in enumerate(characters):
    for j,c2 in enumerate(characters):

        sim = cosine_similarity(
            trajectory_vectors[c1].reshape(1,-1),
            trajectory_vectors[c2].reshape(1,-1)
        )[0][0]

        similarity_matrix[i,j] = sim

print("\nSimilarity Matrix:")
print(similarity_matrix)

# Save similarity matrix
df_sim = pd.DataFrame(similarity_matrix, index=characters, columns=characters)
df_sim.to_csv(os.path.join(results_path,"character_similarity_matrix.csv"))

# ======================================
# 8. Heatmap visualization
# ======================================

plt.figure(figsize=(8,6))

sns.heatmap(
    similarity_matrix,
    xticklabels=characters,
    yticklabels=characters,
    annot=True,
    cmap="coolwarm"
)

plt.title("Character Trajectory Similarity Matrix")

plt.savefig(os.path.join(results_path,"similarity_heatmap.png"))
plt.show()

# ======================================
# 9. Layer-wise similarity matrices
# ======================================

layer_similarities = {}

for l in range(12):

    mat = np.zeros((n,n))

    for i,c1 in enumerate(characters):
        for j,c2 in enumerate(characters):

            e1 = layer_means[c1][l].reshape(1,-1)
            e2 = layer_means[c2][l].reshape(1,-1)

            sim = cosine_similarity(e1,e2)[0][0]

            mat[i,j] = sim

    layer_similarities[l+1] = mat

print("Layer-wise similarity computed")

# Save layer matrices
for l in layer_similarities:
    df_layer = pd.DataFrame(layer_similarities[l], index=characters, columns=characters)
    df_layer.to_csv(os.path.join(results_path,f"layer_{l}_similarity.csv"))

# ======================================
# 10. Average similarity across layers
# ======================================

avg_sim = []

for l in range(1,13):

    mat = layer_similarities[l]

    vals = mat[np.triu_indices(n,1)]

    avg_sim.append(vals.mean())

plt.figure(figsize=(7,4))

plt.plot(range(1,13), avg_sim, marker="o")

plt.xlabel("BERT Layer")
plt.ylabel("Average Character Similarity")
plt.title("Average Inter-Character Similarity Across Layers")

plt.savefig(os.path.join(results_path,"layer_similarity_trend.png"))
plt.show()

# ======================================
# 11. Most similar and most different characters
# ======================================

pairs = []

for i in range(n):
    for j in range(i+1,n):

        pairs.append((characters[i],characters[j],similarity_matrix[i,j]))

pairs_sorted = sorted(pairs, key=lambda x:x[2], reverse=True)

print("\nMost Similar Character Pairs:")
for p in pairs_sorted[:5]:
    print(p)

print("\nMost Different Character Pairs:")
for p in pairs_sorted[-5:]:
    print(p)

# Save pairs
pairs_df = pd.DataFrame(pairs_sorted, columns=["Character1","Character2","Similarity"])
pairs_df.to_csv(os.path.join(results_path,"character_pair_similarity.csv"), index=False)

# ======================================
# 12. Character clustering
# ======================================

X = np.array([trajectory_vectors[c] for c in characters])

kmeans = KMeans(n_clusters=2, random_state=42)
labels = kmeans.fit_predict(X)

cluster_results = []

print("\nCluster assignments:")

for c,l in zip(characters,labels):
    print(c,"-> Cluster",l)
    cluster_results.append((c,l))

cluster_df = pd.DataFrame(cluster_results, columns=["Character","Cluster"])
cluster_df.to_csv(os.path.join(results_path,"character_clusters.csv"), index=False)

# ======================================
# 13. UMAP visualization
# ======================================

reducer = umap.UMAP(random_state=42)

embedding = reducer.fit_transform(X)

plt.figure(figsize=(6,6))

for i,char in enumerate(characters):

    plt.scatter(embedding[i,0], embedding[i,1])
    plt.text(embedding[i,0], embedding[i,1], char)

plt.title("Character Trajectory Visualization (UMAP)")

plt.savefig(os.path.join(results_path,"character_umap.png"))
plt.show()

print("\nAll results saved to:", results_path)

# =========================================================
# JOINT PINN MODEL : LAYER + NARRATIVE TIME
# COMPLETE PIPELINE (FOLDER INPUT VERSION)
# =========================================================

import os
import json
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive

# =========================================================
# 1. MOUNT GOOGLE DRIVE
# =========================================================

drive.mount('/content/drive')

INPUT_FOLDER = "/content/drive/MyDrive/Research_Paper_2/Character_Details/Character_role_tag_with_embeddings"
OUTPUT_DIR = "/content/drive/MyDrive/Research_Paper_2/Character_Details/Joint_Model_Results"

os.makedirs(OUTPUT_DIR, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", DEVICE)

# =========================================================
# 2. LOAD ALL CHARACTER FILES
# =========================================================

def load_character_folder(folder):

    all_data = []

    for file in os.listdir(folder):

        if file.endswith(".json"):

            file_path = os.path.join(folder, file)

            with open(file_path,"r") as f:
                data = json.load(f)

            all_data.extend(data)

    print("Total sentences loaded:", len(all_data))

    return all_data

# =========================================================
# 3. DATASET
# =========================================================

class MahabharataDataset(Dataset):

    def __init__(self, folder):

        self.data = load_character_folder(folder)

        self.samples = []

        for item in self.data:

            layers = np.stack([
                item["embeddings"][f"layer_{i}"]
                for i in range(1,13)
            ])

            metadata = np.array([
                item["parva"] / 18.0,
                item["chapter"] / 100.0,
                item["sentence_number"] / 1000.0
            ])

            self.samples.append({
                "layers": layers,
                "metadata": metadata,
                "character": item["character"]
            })

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        item = self.samples[idx]

        layers = torch.tensor(item["layers"], dtype=torch.float32)
        metadata = torch.tensor(item["metadata"], dtype=torch.float32)

        return layers, metadata, item["character"]

# =========================================================
# 4. JOINT PINN MODEL
# =========================================================

class JointPINN(nn.Module):

    def __init__(self, emb_dim=768):

        super().__init__()

        # input_dim = 768 (emb) + 3 (metadata: parva, chapter, sentence) + 1 (layer_idx) = 772
        input_dim = emb_dim + 4

        self.net = nn.Sequential(
            # First hidden layer: 772 -> 256
            nn.Linear(input_dim, 256),
            nn.Tanh(),

            # Second hidden layer: 256 -> 256
            nn.Linear(256, 256),
            nn.Tanh(),

            # Output layer: 256 -> 768
            nn.Linear(256, emb_dim)
        )

    def forward(self, embedding, metadata, layer_idx):

        batch = embedding.shape[0]

        # Normalized layer index (t)
        layer_tensor = torch.full(
            (batch, 1),
            layer_idx / 12.0,
            device=embedding.device
        )

        # Concatenate: [u(t), metadata, t]
        x = torch.cat([embedding, metadata, layer_tensor], dim=1)

        return self.net(x)



# =========================================================
# 5. PHYSICS INFORMED LOSS
# =========================================================

def pinn_loss(pred, target, prev_emb,
              lambda_data=1.0,
              lambda_smooth=0.1,
              lambda_norm=0.05):

    mse = nn.MSELoss()(pred, target)

    smoothness = torch.mean(
        torch.norm(pred - prev_emb, dim=1)
    )

    norm_diff = torch.mean(
        (torch.norm(pred,dim=1) -
         torch.norm(target,dim=1))**2
    )

    return lambda_data*mse + lambda_smooth*smoothness + lambda_norm*norm_diff

# =========================================================
# 6. TRAINING
# =========================================================

def train_model():

    dataset = MahabharataDataset(INPUT_FOLDER)

    dataloader = DataLoader(
        dataset,
        batch_size=16,
        shuffle=True
    )

    model = JointPINN().to(DEVICE)

    optimizer = optim.Adam(model.parameters(), lr=1e-4)

    epochs = 100

    print("\nStarting Training...\n")

    for epoch in range(epochs):

        total_loss = 0

        for layers, metadata, chars in dataloader:

            layers = layers.to(DEVICE)
            metadata = metadata.to(DEVICE)

            for l in range(11):

                emb_current = layers[:,l,:]
                emb_next = layers[:,l+1,:]

                optimizer.zero_grad()

                pred = model(
                    emb_current,
                    metadata,
                    l+1
                )

                loss = pinn_loss(
                    pred,
                    emb_next,
                    emb_current
                )

                loss.backward()

                optimizer.step()

                total_loss += loss.item()

        avg_loss = total_loss / len(dataloader)

        print(f"Epoch {epoch+1} | Loss: {avg_loss:.6f}")

    return model, dataset

# =========================================================
# 7. SEMANTIC DRIFT ANALYSIS
# =========================================================

def semantic_drift(dataset):

    characters = list(set([d["character"] for d in dataset.data]))

    drift_scores = {}

    for char in characters:

        char_data = [
            d for d in dataset.data
            if d["character"] == char
        ]

        char_data.sort(
            key=lambda x:(x["parva"],x["chapter"],x["sentence_number"])
        )

        n = len(char_data)

        if n < 3:
            continue

        early = char_data[:n//3]
        late = char_data[2*n//3:]

        early_emb = np.mean(
            [d["embeddings"]["layer_12"] for d in early],
            axis=0
        )

        late_emb = np.mean(
            [d["embeddings"]["layer_12"] for d in late],
            axis=0
        )

        sim = cosine_similarity(
            early_emb.reshape(1,-1),
            late_emb.reshape(1,-1)
        )[0][0]

        drift_scores[char] = float(sim)

    return drift_scores

# =========================================================
# 8. RUN COMPLETE PIPELINE
# =========================================================

def run_experiment():

    model, dataset = train_model()

    print("\nRunning Semantic Drift Analysis...\n")

    drift = semantic_drift(dataset)

    for c,v in drift.items():
        print(c, ":", round(v,4))

    torch.save(
        model.state_dict(),
        os.path.join(OUTPUT_DIR,"joint_pinn_model.pt")
    )

    results = {
        "semantic_stability_scores": drift
    }

    with open(
        os.path.join(OUTPUT_DIR,"semantic_drift_results.json"),
        "w"
    ) as f:

        json.dump(results,f,indent=4)

    print("\nResults saved to:", OUTPUT_DIR)

# =========================================================
# RUN
# =========================================================

run_experiment()
